### ISSUE TITLE
NEXTjs adaptation? i am getting an error Token (from anchor project serum) not defined

### ISSUE THREAD

**Issue by fonko** [Fulgurus/candy-machine-v2-responsive-ui#26]
I dig a LOT and almost get to make it work on NEXT js

the problem is with project serum... and I can't figure out what is the deal with this guys

but when I run npm run dev I get this 

> test-candy-next@0.1.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from C:\Users\alfon\OneDrive\Escritorio\nextjs-candy\test-candy-next\.env
@civic/solana-gateway-react:0.7.6
wait  - compiling...
error - ./node_modules/@project-serum/anchor/dist/esm/provider.js:151:0
**Module not found: Can't resolve 'fs'**

Import trace for requested module:
./node_modules/@project-serum/anchor/dist/esm/index.js
./pages/_app.tsx

**Comment by fonko** [comment]
ok, so i was able to understand that project serum doesn't run in server side and I think it was causing this problem.. 

this config for nextjx config file made the trick and now it works

module.exports = {
  webpack5: true,
  webpack: (config) => {
    config.resolve.fallback = { fs: false };

    return config;
  },
};

**Comment by Fulgurus** [comment]
Thanks for the update @fonko it's very appreciated.
